//
//  NewsDataService.swift
//  ecoRecApp
//
//  Created by Artemiy on 11.05.2025.
//

import Foundation

class NewsDataService {
    static let instance: [NewsDataModel] = [
    NewsDataModel(
        cardTitle: "Handover of waste processing aid",
        informationCardTitle: "Purbayan village waste Bank in 2024",
        title: "Handover of waste processing equipment for waste banks and carts, Purbayan Village",
        Image: URL(string: "https://purbayankel.jogjakota.go.id/assets/instansi/purbayankel/article/20240326101827.jpg"),
        contents: "On Friday, March 15, 2024, Purbayan Village, Kemantren Kotagede held a series of events handing over grants for waste processing equipment for waste banks and waste Diggers in Purbayan Village. This activity is a form of support from the Yogyakarta city government through Purbayan village in helping waste bank managers and penggerobak in carrying out their duties and roles in managing waste in the Purbayan Village area. Purbayan village appreciates the existence of waste banks and waste Shodaqoh in the Purbayan Village area in its role to support the Yogyakarta city government's program to reduce and utilize household waste into useful and valuable items. \n\n the event was attended by Mr. Mantri Pamong Praja Kotagede, Mrs. Lurah Purbayan, Chairman of Lpmk Purbayan, waste Bank Faskel board, community leaders in the region, representatives of waste Bank management, waste diggers and Purbayan village officials. \n in his speech, Mr. Mantri Pamong Praja conveyed the importance of citizen awareness supported by the government to manage citizen waste independently, both organic and non-organic from upstream and only residual waste is disposed of at landfills (TPS). In his speech, The Village Head of Purbayan also motivated waste banks and waste shodaqoh in the Purbayan Village area to play a more active role in their respective environments in managing waste, especially with the help of waste field equipment such as garbage sorting carts, organic waste counting machines and garbage sorting bins. \n \n the chairman of Lmpk Purbayan also expressed his gratitude to the Yogyakarta city government for the grant of waste processing equipment to waste Bank administrators and waste diggers, as well as motivating waste banks and waste diggers to further increase their participation in managing and processing waste in order to achieve the target of Purbayan village to be waste-free by 2025. \n \n hopefully with this assistance many provide extensive benefits to the community and make purbayan village into a clean, healthy and prosperous village"),
    NewsDataModel(
        cardTitle: "Pulogadung garbage Bank burned Great",
        informationCardTitle: "Caused a group of teenagers playing firecrackers",
        title: "Garbage Bank in Pulogadung on fire triggered by firecrackers, dozens of fire engines deployed",
        Image: URL(string: "https://asset-2.tstatic.net/tribunnews/foto/bank/images/kebakaran12333.jpg"),
        contents: "Triggered by firecracker coals ignited by children, a garbage bank in the Pulogadung Terminal area, Pulogadung Village/District, East Jakarta burned down on Monday (25/3/2024) night. Sudin Operational Head Of Fire and Rescue in East Jakarta, Gatot Sulaeman, said that children around the location of the firecrackers grabbed the garbage bank, resulting in flames. \n \n the number of piles of plastic bottles and cardboard in the 3×8 square meter garbage bank, made the fire grow quickly in a short time. A total of 11 units of pump cars and 45 East Jakarta Fire and Rescue Sudin personnel were deployed to extinguish the rage of the Red Rooster. \n \n the material loss due to the burning of the garbage bank owned by Pulogadung Terminal was estimated at Rp3 million rupiah. In order to prevent similar incidents residents are advised not to play firecrackers, considering the case of a fire in East Jakarta due to firecrackers is not the first time."),
    NewsDataModel(
        cardTitle: "The city of L. A. has a garbage dump",
        informationCardTitle: "Lampung city government efforts to tackle waste",
        title: "Address the issue of waste, Dlh Bandar lampung collaborates with 10 waste banks",
        Image: URL(string: "https://www.rmollampung.id/uploads/images/2024/03/image_750x_65fed65f71f21.jpg"),
        contents: " Dinas Lingkungan Hidup (DLH) Kota Bandar Lampung menggandeng 10 bank sampah untuk menangani persoalan sampah di Kota Tapis Berseri.\n\n “Kita bekerjasama dengan 10 bank sampah yang ada di Unila, Kemiling, Panjang dan Sukabumi”, Kepala DLH Kota Bandar Lampung, Ahmad Husna, Sabtu (23/3).\n\n Menurutnya dengan adanya bank sampah ini dapat mengurangi volume sampah yang masuk ke TPA Bakung. Tak hanya itu, Ahmad Husna juga mengaku menggandeng peternak magot untuk mengelola sampah makanan. \n\n “Itu semua cukup membantu mengatasi permasalahan sampah,” jelasnya. \n\n Sebelumnya, Pemerintah Kota (Pemkot) Bandar Lampung melalui DLH menyebutkan terjadi peningkatan volume sampah saat bulan suci Ramadan 1445 Hijriah. \n\n “Selama Ramadan ini konsumsi makanan masyarakat meningkat, sehingga volume sampah juga mengalami peningkatkan sekitar 5 persen dari hari biasanya. Biasanya hanya 800 ton, jadi bertambah 20 sampai 25 ton,” ujarnya."),
    NewsDataModel(
        cardTitle: "TPST ngurah rai bali closed by the government",
        informationCardTitle: "TPST ngurah rai bali excess waste",
        title: "TPST ngurah rai Bali closed due to not being able to process waste again",
        Image: URL(string: "https://akcdn.detik.net.id/visual/2024/03/21/sampah-plastik-di-pantai-kedonganan-bali-4_169.jpeg?w=650&q=90"),
        contents: "Tahura Ngurah Rai integrated waste processing facility (TPST), Denpasar, Bali is closed because it is not able to process waste. Denpasar Mayor I Gusti Ngurah Jaya Negara claimed to have been called by the central government regarding the closure of TPST Tahura Ngurah Rai.\n \n living in (TPST Kesiman) Kertalangu if it is not maximal we will replace and close in accordance with applicable regulations, said Jaya Negara at the Dharma Negara Alaya building, Denpasar, Bali, Thursday (21/3).\n \n according to Jaya Negara, the results of waste processing from TPST Kesiman in the form of briquettes are less saleable. The Denpasar city government has difficulty getting buyers of briquettes from the waste. \n \n later, TPST Kesiman was actually demoed because it gave off a bad smell. Jaya Negara hopes that someone will cooperate so that the briquettes from TPST Kesiman can be absorbed. Hopefully with some parties willing to work together can be a new solution, said the PDIP politician. when asked whether TPST Tahura Ngurah Rai will be permanently closed, Jaya Negara replied that it would close permanently by itself. Because, he said, already can not accommodate the volume of garbage. TPST Kesiman and TPST Tahura are targeted to process 450 tons of waste per day. Meanwhile, TPST Padangsambian can process 120 tons of waste per day.\n\n the reason TSPT was closed was because the land that became a waste Bank would be converted into a health center. Because of its strategic location and close to public facilities such as schools. the mayor of Denpasar hopes that the closure of TPST will make residents aware and make the environment clean and controlled."),
    NewsDataModel(
        cardTitle: "Jayapura city generates 241 tons of waste",
        informationCardTitle: "Jayapura city generates tons of garbage",
        title: "DLHK Jayapura says Jayapura generates 241 tons of waste every day",
        Image: URL(string: "https://img.antaranews.com/cache/800x533/2024/03/28/IMG20240328151154.jpg.webp"),
        contents: "The Department of Environment and hygiene (DLHK) of Jayapura city, Papua, said that waste generation in the area was based on the policy and strategy of the Household Waste Management Area and household waste (Jakstrada) in 2023 for the second period to reach 241 tons per day.\n\n head of Section handling waste reduction and waste B3 DLHK Jayapura city Andry Kambu in Jayapura, Thursday, said of the total waste generation is brought to the landfill (TPA) 190 tons per day.\n \n there is a difference of about 50 tons of garbage, but of that amount we handle about five tons per day so that there are still 45 tons of garbage that is still buried in various locations, he said.\n \n according to him, to handle the 45 tons of waste, more extra work is needed from officers in the field to clean up the rest of the waste produced by the community.\n \n because the dirty environment will greatly affect diseases such as dengue fever (DHF), he said.\n\n he explained that a clean environment will reduce the mosquito population so that infectious diseases such as dengue can be resolved.\n \n concrete steps that we will take to create a clean environment is to clean up potentially dirty areas or clogged drains that will be cleaned in collaboration with RT/RW, he said.\n\n Dia added that it is hoped that this action will prevent the growth or spread of dengue fever in Jayapura city.")
    ]
}
